name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run deploy

  merge:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Configure Git
      run: |
        git config --global user.email "rikialamo@gmial.com"
        git config --global user.name "Ricardo"

    - name: Merge main into gh-pages
      run: |
        if git remote | grep origin; then git remote set-url origin https://github.com/rikialamo/TFGAngular; else git remote add origin https://github.com/rikialamo/TFGAngular; fi
        git fetch origin main
        git checkout gh-pages
        git merge origin/main --no-ff
        git push origin gh-pages

  deploy:
    runs-on: ubuntu-latest
    needs: merge

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/TFGAngular
